theme: jekyll-theme-minimal
title: 乡愁永酒
description: wcj365@gmail.com
baseurl: /love
email: "wcj365@gmail.com"
#header:
#  image: "/assets/images/ocean.jpeg"
logo: "/assets/images/ocean.jpeg"
github:
  is_project_page: false
google_analytics: 
