theme: jekyll-theme-minimal
title: 乡愁永酒
# description: 穆阳猴诗文集
baseurl: /love
email: "wcj365@gmail.com"
header:
  image: /assets/images/ocean.jpeg
logo: "/assets/images/ocean.jpeg"
github:
  is_project_page: false
